---
version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: bowlpickem-dev
      POSTGRES_USER: bowlpickem
      POSTGRES_PASSWORD: bowlpickem
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5435:5432"
    volumes:
      - dev-pg-datavolume:/var/lib/postgresql/data/pgdata

  test-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DATABASE: bowlpickem-test
      POSTGRES_USER: bowlpickem
      POSTGRES_PASSWORD: bowlpickem
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5436:5432"
    volumes:
      - test-pg-datavolume:/var/lib/postgresql/data/pgdata

volumes:
  dev-pg-datavolume:
  test-pg-datavolume:
