import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import styles from '../styles/Home.module.scss'
import BigLogo from '../assets/images/bowlpickem-logo.svg';
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const games = trpc.games.bowlGames.useQuery();
  const participants = trpc.participants.allParticipants.useQuery();

  const renderGames = () => {
    if (games.isLoading) {
      return <div>Games loading...</div>;
    }

    return (
      <div className="text-white">
        {games.data?.games.map((matchup) => (
          <div key={matchup.id}>
            {matchup.name}: {matchup.homeTeam.name} vs {matchup.awayTeam.name}
          </div>
        ))}
      </div>
    );
  };

  const renderParticipants = () => {
    if (participants.isLoading) {
      return <div>Participants loading...</div>;
    }

    return (
      <div className="text-white">
        {participants.data?.participants.map((participant) => (
          <div key={participant.id}>
            {participant.name}
          </div>
        ))}
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Bowl Pick'em 2022-23</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-black">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-black sm:text-[5rem]">
            Very Cool <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <Image src={BigLogo.src} alt="test" width={390} height={160} />
          <div className={styles['quick-test']}>
            Test
          </div>
          <div className="flex flex-col items-center gap-2">
            {renderGames()}
            {renderParticipants()}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
