---
name: Sync Webhooks

on:
  schedule:
    # Every hour on the :30
    - cron: "30 * * * *"
    # # Every 2 hours on the 00
    # - cron: "0 */2 * * *"
    # # Once a week
    # - cron: "0 0 * * 1"

jobs:
  sync-games:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Bowl Games
        if: github.event.schedule == '30 * * * *'
        run: |
          curl -X POST -ss \
            -H "Authentication: token $WEBHOOK_SECRET" \
            "${DEPLOYMENT_URL}/api/sync/sync-bowl-games"
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          DEPLOYMENT_URL: ${{ secrets.DEPLOYMENT_URL }}
